### ISSUE TITLE
conquest

### ISSUE THREAD

**Issue by mmiller786** [Yatekko/Adelheid#23]
**Is your feature request related to a problem? Please describe.**
Problem: am sometimes too lazy to log in to find out what place Windurst is in :)

**Describe the solution you'd like**
/conquest blank = list 3 countries and their place in conquest, specific area = who is leading that area

**Describe alternatives you've considered**
Asking people on discord; so far, fruitless.

**Comment by Yatekko** [comment]
Needs some collaboration with other devs on the database.  Also references #7
